spring:
  application:
    name: ApiGateway
  cloud:
    gateway:
#Cấu hình với Load Balancer
      discovery:
        locator:
          enabled: true
      routes:
        - id: EmployeeService
          uri: lb://EmployeeService
          predicates:
            - Path=/api/v1/employees/**
#Cấu hình thủ công
#      routes:
#        - id: EmployeeService
#          uri: http://localhost:9002
#          predicates:
#            - Path=/api/v1/employees/**
server:
  port: 8080
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true