version: '3.3'
services:
  axonserver-1:
    image: axoniq/axonserver:latest
    hostname: axonserver-1
    ports:
      - '8024:8024'
      - '8124:8124'
      - '8224:8224'
    networks:
      - axon-demo

networks:
  axon-demo:
    driver: bridge