spring:
  application:
    name: NotificationService
  kafka:
    consumer:
      group-id: notification-group
server:
  port: 9003
eureka:
  client:
    service-url:
#      defaultZone: http://localhost:8761/eureka
      defaultZone: http://discoverserver:8761/eureka
axon:
  axonserver:
    servers: axonserver:8124