spring:
  application:
    name: NotificationService
  kafka:
    consumer:
      group-id: notification-group
server:
  port: 9003
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka