spring:
  application:
    name: BookService
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bookdb
    username: root
    password: root
  liquibase:
    url: jdbc:mysql://localhost:3306/bookdb
    user: root
    password: root
    change-log: classpath:/db/changelog/changelog-master.xml
    enabled: true
server:
  port: 9001
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
#      defaultZone: http://discoverserver:8761/eureka
#Swagger
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
#axon:
#  axonserver:
#    servers: axonserver:8124